# Generated by Django 6.0.1 on 2026-01-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_hraccesscode_company_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('ISSUE', 'Issue'), ('CONCERN', 'Concern'), ('QUESTION', 'Question'), ('SUGGESTION', 'Suggestion')], max_length=20),
        ),
    ]
