"""
Django settings for anonplatform project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Try importing dj_database_url for production database support
try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Prefer a real ".env" (local secrets), but fall back to "env.example" for easy dev setup.
load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR / "env.example")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()] or ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'submissions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'submissions.middleware.RateLimitMiddleware',  # Rate limiting for submissions
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'anonplatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'anonplatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use PostgreSQL in production if DATABASE_URL is set, otherwise SQLite for development
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL and dj_database_url:
    # Parse DATABASE_URL and ensure it's a valid PostgreSQL connection
    try:
        db_config = dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=0,  # Disable connection pooling to avoid hanging connections
            conn_health_checks=False,  # Disable health checks to avoid slow startup
        )
        # Add connection timeout settings to prevent hanging
        if 'OPTIONS' not in db_config:
            db_config['OPTIONS'] = {}
        db_config['OPTIONS']['connect_timeout'] = 5  # 5 second connection timeout
        db_config['CONN_MAX_AGE'] = 0  # Don't reuse connections (prevents hanging)
        DATABASES = {
            'default': db_config
        }
    except Exception as e:
        # Fallback to SQLite if database URL parsing fails
        import sys
        print(f"Warning: Failed to parse DATABASE_URL: {e}", file=sys.stderr)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Email Configuration
# Railway blocks outbound SMTP connections, so we use API-based email services instead
# Set DJANGO_EMAIL_BACKEND to one of:
# - "anonplatform.email_backends.ResendEmailBackend" (for Resend API - easiest setup)
# - "anonplatform.email_backends.SendGridEmailBackend" (for SendGrid API)
# - "anonplatform.email_backends.MailgunEmailBackend" (for Mailgun API)
# - "django.core.mail.backends.smtp.EmailBackend" (for SMTP - works locally but not on Railway)
# - "django.core.mail.backends.console.EmailBackend" (for development - prints to console)

# Prefer API-based email services in production (Railway blocks SMTP)
EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND")
if not EMAIL_BACKEND:
    if os.environ.get("RESEND_API_KEY"):
        EMAIL_BACKEND = "anonplatform.email_backends.ResendEmailBackend"
    elif os.environ.get("SENDGRID_API_KEY"):
        EMAIL_BACKEND = "anonplatform.email_backends.SendGridEmailBackend"
    elif os.environ.get("MAILGUN_API_KEY") and os.environ.get("MAILGUN_DOMAIN"):
        EMAIL_BACKEND = "anonplatform.email_backends.MailgunEmailBackend"
    else:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "no-reply@example.com")
HR_NOTIFY_EMAILS = [e for e in os.environ.get("HR_NOTIFY_EMAILS", "").split(",") if e]

# Resend API Configuration (recommended - easiest setup)
# Get your API key from: https://resend.com/api-keys
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")

# SendGrid API Configuration
# Get your API key from: https://app.sendgrid.com/settings/api_keys
SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", "")

# Mailgun API Configuration
# Get your API key and domain from: https://app.mailgun.com/app/dashboard
MAILGUN_API_KEY = os.environ.get("MAILGUN_API_KEY", "")
MAILGUN_DOMAIN = os.environ.get("MAILGUN_DOMAIN", "")

# SMTP Email Configuration (for Gmail/Google Workspace - works locally but NOT on Railway)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))  # 10 second timeout to prevent hanging

# Anonymous access gate
COMPANY_ACCESS_CODE = os.environ.get("COMPANY_ACCESS_CODE", "123456")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings - HTTPS Enforcement & Data Encryption
# These settings ensure all pages use HTTPS and encrypt data in transit

# Force HTTPS in production (disable in development)
SECURE_SSL_REDIRECT = not DEBUG  # Redirect all HTTP to HTTPS
# For Railway/Heroku/Fly.io behind proxy - all use X-Forwarded-Proto header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None

# HTTP Strict Transport Security (HSTS) - Force browsers to use HTTPS
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
SECURE_HSTS_PRELOAD = True  # Allow HSTS preload list

# Content Security Policy (CSP) - Prevent XSS attacks
# Note: For full CSP support, install django-csp package
# For now, we rely on Django's built-in XSS protection
# SECURE_CONTENT_SECURITY_POLICY = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"

# Browser Security Headers
SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
X_CONTENT_TYPE_OPTIONS = 'nosniff'  # Prevent MIME sniffing
X_XSS_PROTECTION = '1; mode=block'  # XSS protection

# Cookie Security - Only send cookies over HTTPS
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to cookies
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF token
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# CSRF trusted origins for Railway/production
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Referrer Policy - Control referrer information
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Cross-Origin Policies
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# Cache configuration (for rate limiting)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'submissions': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
